config/routes.rb
Konverents::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/facebook' => 'users/omniauth_callbacks#passthru'
    get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#passthru'
    get "sign_in",  :to => "devise/sessions#new", :as => :login
    get "sign_up",  :to => "devise/registrations#new"
    get "sign_out", :to => "devise/sessions#destroy", :as => :logout
  end

  root :to => 'home#index'

  resources :events do
      resources :tracks do
        resources :occurrences
      end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  attr_accessor :other
  
  before_create :validate_created_by_other
  belongs_to :user
  has_many :tracks
  
  validates_presence_of :title, :user
  
  def owned_by? owner
    owner.present? && user.id == owner.id
  end
  
  private
  def validate_created_by_other
    msg = "Trying create an event with other user"
    raise Exceptions::CreatedByOtherUser.new(msg) unless self.user.eql? @other
  end
  
end

app/models/exceptions.rb
module Exceptions
  class CreatedByOtherUser < StandardError
  end
end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
  belongs_to :track
  validates_presence_of :hour, :description
end

app/models/track.rb
class Track < ActiveRecord::Base
  
  belongs_to :event
  has_many :occurrences
  
  validates_presence_of :event, :date
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def self.find_for_facebook_oauth(email_from_facebook, signed_in_resource=nil)
        
    unless user = User.find_by_email( email_from_facebook )
      user = User.new(:email => email_from_facebook,
                      :password => Devise.friendly_token[0,20])
      user.skip_confirmation! 
      user.save           
    end
    
    user

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  
  before_filter :find_event, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_owner!, :only => [:edit, :update, :destroy]
  
  before_filter :populate_event_on_params, :only => [:create]
  
  respond_to :html, :json
  
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def show
  end
  
  def edit
  end
  
  rescue_from Exceptions::CreatedByOtherUser, :with => :record_not_created
  def create
    @event = Event.create params[:event].merge(:other => current_user)
    respond_with @event
  end
  
  def update
    @event.update_attributes params[:event]
    respond_with @event
  end
  
  def destroy
    @event.destroy
    redirect_to :action => :index
  end
  
  private
  
  def populate_event_on_params
    params[:event] = {} unless params[:event].present?
  end
  
  def record_not_created exception
    respond_with_error(exception.message) and return
  end
  
  def find_event
    @event = Event.find params[:id]
  end
  
  def authenticate_owner!
    respond_with_error and return unless @event.owned_by?(current_user)
  end
  
  def respond_with_error(message = "Unauthorized User", error_code = :unauthorized)
    Rails.logger.info "RESPONDING WITH ERROR #{message} and #{params}"
    respond_to do |format|
      format.html {
        redirect_to(events_path, :status => error_code, :flash => { :alert => message } )
      }
      format.json { render :json => { :message => message}, :status => error_code }
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  

  before_filter :authenticate_user!  

  before_filter :authenticate_owner!, :only => [:update, :edit]

  before_filter :find_event, :find_track

  respond_to :html, :json

  def index
  	@occurrences = Occurrence.all
  end

  def show
  	@occurrence = Occurrence.find(params[:id])
  end

  def new
  	@occurrence = Occurrence.new
  end

  def create
  	@occurrence = Occurrence.create(params[:occurrence])
  	respond_with @occurrence
  end

  def edit
  	@occurrence = Occurrence.find(params[:id])
  end

  def update
  	@occurrence = Occurrence.find(params[:id])
  	@occurrence.update_attributes(params[:occurrence])
  	respond_with @occurrence
  end

  def delete
  	@occurrence = Occurrence.find(params[:id])
  	@occurrence.destroy
  	respond_with @occurrence
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_track
    @track = Track.find(params[:track_id])
  end

  private

  def authenticate_owner!
    unless @occurrece.owned_by?(current_user)
      respond_with({:error=>'unauthorised'}, :status => :forbidden) and return
    end
  end

end

app/controllers/tracks_controller.rb
# encoding: UTF-8
class TracksController < ApplicationController

  before_filter :find_event
  respond_to :html, :json

  def index
    @tracks = @event.tracks
    respond_with @tracks
  end
  
  def show
    @track = Track.find params[:id]
  end
  
  def new
    @track = Track.new :event_id => @event
  end
  
  def create
    @track = Track.new params[:track]
    @track.save
    respond_with @track, :location => event_track_url(@event.id, @track.id)
  end
  
  def find_event
    @event = Event.find params[:event_id]
  end

  def delete
		@track = Track.find params[:id]
		@track.destroy
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :authenticate_user!

  def facebook
    
    @email = env["omniauth.auth"]['extra']['raw_info']['email']
    @user = User.find_for_facebook_oauth(@email, current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def passthru
    logger.debug "Inside Passthrought"
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    logger.debug "After render"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_if(current_menu)
    controller_name == current_menu ? " active" : "" 
  end
end

app/helpers/components_helper.rb
module ComponentsHelper
  class ComponentsFormBuilder < ActionView::Helpers::FormBuilder
    def input_comp(name_attr, options = {})
      "
      <div class='field'>
        #{ label(name_attr, options[:label]) }
        #{ text_field(name_attr, options) }
      </div>
      "
      .html_safe
    end

    def text_comp(name_attr, options = {})
      "
      <div class='field'>
        #{ label(name_attr, options[:label]) }
        #{ text_area(name_attr, options) }
      </div>
      "
      .html_safe
    end
  end
  
  ActionView::Base.default_form_builder = ComponentsFormBuilder
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
end

app/views/events/index.html.erb
<h2>All events</h2>
<ul>
	<% @events.each do |event| %>
	<li> <%= link_to event.title, event_tracks_path(event.id) %></li>
	<% end%>
</ul>

app/views/events/new.html.erb
<h2>Add new event</h2>

<%= form_for @event, :url => { :action => :create } do |f| %>

  <%= f.input_comp :title, :label => "Título do evento" %>

  <%= f.submit 'Salvar' %>

<% end %>

app/views/home/index.html.erb
Oi inicial

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <%= render "layouts/menu" %>
    <%= link_to "konverents", root_path, :class => "name" %>
    <h1><%= @page_title || controller.controller_name.capitalize %></h1>
  </div>
</header>

app/views/layouts/_menu.html.erb
<nav>
  <%= link_to "Home", root_path, :class => active_menu_if("home") %>
  <%= link_to "Events", events_path, :class => active_menu_if("events") %>
  <% if user_signed_in? %>
	<%= link_to "Sign out", logout_path, :class => active_menu_if("sessions") %>
  <% else %>
	<%= link_to "Sign in", login_path, :class => active_menu_if("sessions") %>
  <% end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konverents - Kind Of New Victorious Events Really Excellent, Nice and Totally Smooth</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Shadows+Into+Light" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<section><%= yield %></section>

<%= render "layouts/footer" %>

</body>
</html>

app/views/occurrences/delete.html.erb
<h1>Occurrences#delete</h1>
<p>Find me in app/views/occurrences/delete.html.erb</p>

app/views/occurrences/edit.html.erb
<h1>Occurrences#edit</h1>
<p>Find me in app/views/occurrences/edit.html.erb</p>

app/views/occurrences/index.html.erb
<h1>Occurrences#index</h1>
<p>Find me in app/views/occurrences/index.html.erb</p>

app/views/occurrences/new.html.erb
<h1>Occurrences#new</h1>
<p>Find me in app/views/occurrences/new.html.erb</p>

app/views/tracks/index.html.erb
<%= link_to "Create Track", new_event_track_path(@event) %>


<% @tracks.each do |track| %>
	<div id="track_<%= track.id %>">
		<%= link_to "Exibir #{track.title}", event_track_path(@event.id, track.id) %>
		<%= link_to "Alterar Track", edit_event_track_path(@event.id, track.id) %>
		<div class="track_date"> <%= track.date %> </div>
		<div class="track_local"> <%= track.local %> </div>
		
		<ul>
			<% track.occurrences.each do |occurrence| %>
			<li>
				<%= occurrence.hour %> - <%= occurrence.description %>
			</li>
			<% end %>
		</ul>
		
	</div>
<% end %>

app/views/tracks/new.html.erb
<h2><%= @event.title %></h2>

<%= form_for @track, :url => { :action => "create" } do |f| %>

  <%= f.hidden_field :event_id, :value => @track.event_id %>

  <%= f.input_comp :title %>
  <%= f.input_comp :date %>

  <%= f.submit "Create" %>
<% end %>

app/views/tracks/show.html.erb
<%= @track.title %>
<%= @track.date %>

app/views/tracks/view.html.erb
<%= @track.title %>
<%= @track.date %>